export default {
//    mixxchaimin:require('../assest/Images/mixxchaimin.png'),
//    graterthan:require('../assest/Images/graterthan.png'),
//    lock:require('../assest/Images/lock.png'),
//   facebook:require('../assest/Images/facebook.png'),
//    google:require('../assest/Images/google.png'),
//    deliveryboy:require('../assest/Images/deliveryboy.png'),
//    deleverymainww:require('../assest/Images/deleverymainww.png'),
//    otpimage:require('../assest/Images/otp.png')
menuimage:require('../assest/Images/menu.jpg'),
cartimage:require('../assest/Images/cart.jpg'),
onionimage:require('../assest/Images/onion.jpg'),
swiper1:require('../assest/Images/swiper1.jpg'),
potatoimage:require('../assest/Images/potato.jpg'),
greenimage:require('../assest/Images/green.jpg'),
dryimage:require('../assest/Images/dry.png'),
fruitsimage:require('../assest/Images/fruits.png'),
swiper2:require('../assest/Images/swiper2.png'),
swiper3:require('../assest/Images/swiper3.png'),
swiper4:require('../assest/Images/swiper4.png'),
home:require('../assest/Images/home.png'),
category:require('../assest/Images/category.png'),
favourites:require('../assest/Images/fav.png'),
cart1:require('../assest/Images/cart1.png'),
location:require('../assest/Images/location.png'),
leftarrow:require('../assest/Images/leftarrow.png'),
filter:require('../assest/Images/filter.png'),
search:require('../assest/Images/search.png'),
empty:require('../assest/Images/empty.png'),
ifreshlogo:require('../assest/Images/freshlogo.png'),
home1:require('../assest/Images/hometab.png'),
notification:require('../assest/Images/notification.png'),
wallet:require('../assest/Images/wallet.png'),
track:require('../assest/Images/track.png'),
refer:require('../assest/Images/refer.png'),
referfriend:require('../assest/Images/referfriend.png'),
code:require('../assest/Images/code.png'),
contact:require('../assest/Images/contact.png'),
about:require('../assest/Images/about.png'),
rate:require('../assest/Images/rate.png'),
share:require('../assest/Images/share.png'),
faq:require('../assest/Images/faq.png'),
terms:require('../assest/Images/terms.png'),
privacy:require('../assest/Images/privacy.png'),
list:require('../assest/Images/list.png'),
logout:require('../assest/Images/logout.png'),
}